[tool.poetry]
name = "hexlet_code"
version = "0.1.0"
description = "Project 2"
authors = ["NeoVic2006 <NeoVic2006@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.6"


[tool.poetry.dev-dependencies]
proj = "main_script"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
