[tool.poetry]
name = "NeoVic2006-project-CLI"
version = "0.1.0"
description = "start"
authors = ["NeoVic2006 <NeoVic2006@gmail.com>"]

packages = [
  { include = "main_code" },
]



[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.8.4"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
gendiff = "main_code.gendiff:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
