[tool.poetry]
name = "python-project-lvl2"
version = "0.1.0"
description = "start"
authors = ["NeoVic2006 <NeoVic2006@gmail.com>"]

packages = [
  { include = "test_folder" },
]



[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.8.4"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
proj = "test_folder.main_script:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
