[tool.poetry]
name = "NeoVic2006-project-CLI"
version = "0.1.3"
description = "gendiff: second Hexlet project"
authors = ["NeoVic2006 <NeoVic2006@gmail.com>"]

packages = [
  { include = "gendiff" },
]



[tool.poetry.dependencies]
python = "^3.6"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
