name: Python CI

on:
  - push
  - pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8]
        steps:
            - uses: actions/checkout@v2
              
            - name: Python ${{ matrix.python-version }} installation
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Dependencies check
              run: |
                pip install poetry
                make install
                poetry install
                
            - name: Lint command
              run: |
                make lint
            - name: Run Tests
              #working-directory: ./tests
              run: | 
                pwd
                poetry run pytest -q tests/tests_for_JSON.py
                poetry run pytest --cov=gendiff --cov-report xml tests/tests_for_JSON.py
                CC_TEST_REPORTER_ID: 2fc0fe35bdf5f669686a3e4d1ac4053a41e4b7ba26f5dbfb3ecbc0a312da78ed
          