name: Python CI

on:
  - push
  - pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8]
        steps:
            - uses: actions/checkout@v2
              
            - name: Python ${{ matrix.python-version }} installation
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Dependencies check
              run: |
                pip install poetry
                make install
                
            - name: Lint command
              run: |
                make lint
            - name: Run Tests
              run: | 
                make test

            - name: Publish code coverage
              uses: paambaati/codeclimate-action@v2.7.5
              env:
                CC_TEST_REPORTER_ID: ${{ secrets.SuperSecret }}